---
- name: Check if libdrm build dir exists
  stat:
    path: "{{ sources }}/drm/build"
  register: drm_build
- name: drm
  when: git_drm.changed or "drm" in rebuild or not drm_build.stat.exists
  block:
    - name: Configure drm
      args:
        chdir: "{{ sources }}/drm"
      shell:
        "{{ playbook_dir }}/../conf_drm.sh"
    - name: Build+Install drm
      args:
        chdir: "{{ sources }}/drm"
      shell:
         ninja -C build install
  rescue:
    - name: Cleanup on errors
      ansible.builtin.file:
        path: "{{ sources }}/drm/build"
        state: absent
    - name: Fail
      ansible.builtin.command: /bin/false